---
title: "final ML"
author: "Zac Macintyre"
date: "6/9/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
fires = read.csv("ForestFires.csv")
head(fires)
```

```{r}

colSums(is.na(fires))

```
As we said in the presentation there is no missing values just doing a little check

# This section is me doing some initial data visualization and somre data analysis

```{r}
barplot(table(fires$month))
barplot(table(fires$day))
```
```{r}
summary(fires)
```

```{r}
par(mfrow=c(2,2))
plot(fires$rain, fires$area)
plot(fires$temp, fires$area)
plot(fires$FFMC, fires$area)
plot(fires$DMC, fires$area)
```
```{r}
par(mfrow=c(2,2))
plot(fires$DC, fires$area)
plot(fires$ISI, fires$area)
plot(fires$wind, fires$area)
plot(fires$RH, fires$area)
```

```{r}
fires_matirx = fires[,-c(3,4)]
corelation_m = cor(fires_matirx, use='pairwise.complete.obs')
lower = lower.tri(fires_matirx)
corelation_m
hist(corelation_m[lower], xlab = 'correlations of lower matrix')
```

